// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-17 21:12:32
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Alert is the golang structure of table a_alert for DAO operations like Where/Data.
type Alert struct {
	g.Meta    `orm:"table:a_alert, do:true"`
	Alert      interface{} // metric，主键
	Desc       interface{}
	Threshold  interface{} // 阈值
	Default    interface{}
	State      interface{}
  Info       interface{}
	CreatedAt  *gtime.Time // 创建时间
	UpdatedAt  *gtime.Time // 更新时间
}
