// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-17 21:12:32
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Alert is the golang structure for table a_alert.
type Alert struct {
	Alert       string      `json:"alert"       description:"报警名称，主键"`
	Desc        string      `json:"desc"        description:"报警说明"`
	Threshold   string      `json:"threshold"   description:"默认阈值, 以 json 形式存储 "`
	Default     int         `json:"default"     description:"默认是否报警，需要生成的 metrics 和 prometheus 中的 rule 配合使用"`
	State       int         `json:"state"       description:"0：关闭，1：开启，需要生成的 metrics 和 prometheus 中的 rule 配合使用"`
	Info        string      `json:"info"        description:"报警关闭的原因"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:"创建时间"`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:"修改时间"`
}
